### ISSUE TITLE
pixelWidthCalculator.html file added on build

### ISSUE THREAD

**Issue by Merlin04** [pablofrommars/GGNet#16]
When I build my Blazor WASM app with GGNet, a file called `_content/GGNet/pixelWidthCalculator.html` is added. What is it for, and if it is not used is there a way to remove it?

**Comment by pablofrommars** [comment]
It's a script to evaluate rendered width of ASCII characters for a given font. GG.Net approximates length of text from the output of the script. I am planning to replace this static approach with some optional JS interaction when ligature and kerning needs to be taken into account for better rendering accuracy.
