### ISSUE TITLE
Chart vertical height, horizontal axis spacing [User help]

### ISSUE THREAD

**Issue by slater1** [pablofrommars/GGNet#17]
Hey Pablo, thanks for creating this project. It's really promising for my use case. I'm creating a pain chart for physical therapy patients. I started from the SPY example and got this far:

![image](https://user-images.githubusercontent.com/2089725/92651199-cddef000-f2ba-11ea-8d10-8e0467974203.png)

``` csharp
        data = Plot.New(source, x: o => o.When, y: o => o.Pain)
            .Title("Pain Over Time")
            .Geom_Area(alpha: 0.3)
            .Geom_VLine(x: o => string.IsNullOrWhiteSpace(o.Activity) ? default : o.When,
                    color: "#FF00D9",
                    lineType: LineType.Dashed)
            .YLab("Level")
            .XLab("Date")
            .YLim(min: 0, max: 10)
            .Caption("Source: Patient")
            .Theme(theme);
```

One key difference for me is I am using ```LocalDateTime``` instead of just ```LocalDate```.

My questions are

1. Can I adjust the horizontal axis label spacing or rotation? The text is so crammed it looks like a solid bar.
2. Can I adjust the vertical height of the chart to fill the window? Would this be better done with CSS or the chart Height property?

I found a solution to some of my questions by Googling for ggplot, but not all solutions seem to map to ggnet. It's much harder to Google for ggnet, so here I am.

Thanks!

**Comment by pablofrommars** [comment]
Hi!

Thanks for your interest.

1. Rotation is on my roadmap. The number of labels is "automatically" calculated, but the heuristic I came up with doesn't fit your use case. It would be straight forward to add a parameter for users to pass to the scale.

2. I guess it can be best achieved with CSS, should not be to hard to come up with a solution that would preserve aspect ratios as well.

I currently don't have too much time to dedicate to the project. But I am planning in a not to distant future a big push to address some of the open issues and add a bunch features that I will need for my next project.

**Comment by slater1** [comment]
Thanks for the quick feedback.

**Comment by slater1** [comment]
I found a solution the using ```formatter``` parameter of ```Scale_X_Discrete```. The idea is to map a desired set of LocalDateTimes e.g. "every 4 days" onto the data set.

``` csharp
    protected override void OnInitialized()
    {
        _source = new Source<PainTime>();
        var data = PainService.Data
            .OrderBy(p => p.When)
            .ToList();

        foreach (var p in data)
        {
            _source.Add(p);
        }

        var selection = new List<PainTime>();
        LocalDateTime temp = data.First().When;

        foreach (var pt in data)
        {
            if (pt.When >= temp)
            {
                selection.Add(pt);
                temp = temp.PlusDays(4);
            }
        }

        // Start with all empty labels
        var allLabels = data
            .GroupBy(pt => pt.When)          // Make
            .Select(group => group.First())  // unique
            .ToDictionary(pt => pt.When, pt => string.Empty);

        // Prevent KeyNotFoundException when LocalDateTime == default 
        // because Activity was NullOrWhiteSpace
        allLabels[default] = default;

        // Add labels only for selected dates
        var selectionLabels = selection
            .ToDictionary(pt => pt.When, pt => pt.When.Date.ToString("M-dd", default));

        foreach (var label in selectionLabels)
        {
            allLabels[label.Key] = label.Value;
        }

        var labeller = new Labeller<LocalDateTime>(allLabels);

        _data = Plot.New(_source, x: o => o.When, y: o => o.Pain)
            .Title("Pain Over Time")
            .Geom_Area(alpha: 0.3)
            .Geom_VLine(x: o => string.IsNullOrWhiteSpace(o.Activity) ? default : o.When,
                    //label: o => o.Activity,
                    color: "#FF00D9",
                    lineType: LineType.Dashed)
            .Scale_X_Discrete(formatter: labeller)

            .YLab("Level")
            .XLab("Date")
            .YLim(min: 0, max: 10)
            .Caption("Source: Patient")
            .Theme(Theme.Default());
    }
```
![image](https://user-images.githubusercontent.com/2089725/92790486-cfbbb880-f379-11ea-8246-7c81ef7ed2fe.png)
