### ISSUE TITLE
Has this project been discontinued?

### ISSUE THREAD

**Issue by netcorefan** [pablofrommars/GGNet#18]
It's not an issue, but a question.

**Comment by pablofrommars** [comment]
Hi netcorefan,

The project has not been discontinued. I am hoping to upgrade to net5 as soon as time allows.

Would you mind explaining why you ask? I am listening to users feedback.

Thanks for your interest.

**Comment by netcorefan** [comment]
I said it because the last update was on May 28 and issues since June 7 had not received a response. Also I had seen that @jan-ai had made a fork and he was patching his written issues there.
I'm glad that project continues.

**Comment by netcorefan** [comment]
Hi,

Are you going to upgrade to net 5  or waiting for net 6?

**Comment by pablofrommars** [comment]
At this point waiting for net6 and Maui. Thanks for your renewed interest.

**Comment by pablofrommars** [comment]
@netcorefan Gonna work again on it sooner than expected. Is there anything you want to see with the next versions apart from updating frameworks?

**Comment by netcorefan** [comment]
Hi Pablo,

 



I was interested in using this project because I found it very powerful, but I haven't used it yet because I didn't see ongoing support and I don't have time at this point to dig into the code.
If I have seen in the code that everything is based on the generation of svg and that part has been greatly enhanced in .net 6, that is why I understood that you say in the last message that you were waiting for the final version of .net 6




I would add that I see the donut charts interesting as a new component by itself.



Anyway, when you start the project to update itself regularly, I'm sure I'll be proposing things to you, and if I get time, maybe I can propose some improvements in the code.



thanks for asking

regards.



 

Enviar: domingo 13 de junio de 2021 a las 15:30
De: "Pablo Belin" ***@***.***>
Para: "pablofrommars/GGNet" ***@***.***>
CC: "netcorefan" ***@***.***>, "Mention" ***@***.***>
Asunto: Re: [pablofrommars/GGNet] Has this project been discontinued? (#18)


 

@netcorefan Gonna work again on it sooner than expected. Is there anything you want to see with the next versions apart from updating frameworks?

**Comment by pablofrommars** [comment]
@netcorefan I upgraded to .net 5 about two month ago, have a look at 8ed434b.

I mostly use the library in .net interactive inside viscose, so expect future work to be focused on better support for that use case.

Concerning donut charts, I will not implement them as there are more often than not poor choice of representation (see https://www.data-to-viz.com/caveat/pie.html for more details)
