### ISSUE TITLE
BoxPlots

### ISSUE THREAD

**Issue by GPT-John** [pablofrommars/GGNet#19]
Are there any plans to implement a BoxPlot to accompany those Violin plots. It would be mighty useful.

**Comment by pablofrommars** [comment]
Hi!

If you are comfortable computing the percentiles at the data source level, you can probably abuse the candlestick geom for your purpose.

I will keep the request on the list for when my effort to modernise the library is in motion. I am currently looking for a new job so I can’t promise anything on the timeline. I am using the library myself, the project is not dead.

thanks for your interest
