### ISSUE TITLE
GGNet Choropleth State Map

### ISSUE THREAD

**Issue by isabellachiarav** [pablofrommars/GGNet#20]
Thank you for the work you have done in GGNet. My co-worker and I are trying to implement a map of the United States divided into states. We’re looking for a way to implement this, but we can’t seem to find out how the GGNet library draws the countries. Is it possible to do this? Please get back to us when convenient for you.

**Comment by pablofrommars** [comment]
Hi Isabella,

Happy to hear the library is being used.

If you have a look at GGNet.NaturalEarth, the country record holds polygon shapes. You would need to have the states defined in a similar fashion. Data for it should be publicly available, what scale are you interested in?

In case you have not seen it yet, https://pablofrommars.github.io/examples/choropleth would be the relevant example from the doc.

Keep me posted on your progress.

**Comment by pablofrommars** [comment]
Would you be able to share some code? I am not sure I understand the question.
