### ISSUE TITLE
Time series with subminute resolution

### ISSUE THREAD

**Issue by 23min** [pablofrommars/GGNet#4]
Love your library and I'm successfully using it for some charts. Now I ran into a problem.

A line chart with X axis defined as `Scale_X_DateTime_Discrete `will fault if the data points have X values with subminute resolution (i.e. with a 'seconds' part in the DateTime).

Using the following:

```
    "Metrics": [
        {
            "Timestamp": "2020-04-30T13:30:00+02:00",
            "Series": "broker",
            "Value": "10"
        },
        {
            "Timestamp": "2020-04-30T15:30:05+02:00",
            "Series": "broker",
            "Value": "40"
        },
        {
            "Timestamp": "2020-05-01T15:50:10+02:00",
            "Series": "broker",
            "Value": "50"
        }
    ],
```

Will cause output errors like the following in the console:

`Error: <line> attribute x1: Expected length, "NaN".`
`Error: <path> attribute d: Expected number, "M NaN 123.80198019…".`

When I set the Seconds part to 0, the chart renders OK.

My code (experimented with limits to no avail):

```
data = Plot.New(source, x: o => o.Timestamp, y: o => o.Value)
            .Geom_Line(source, width: 2, x: o => o.Timestamp, y: o => o.Value)
            .XLab("Timestamp")
            .YLab("Value")
            //.Scale_X_Discrete_DateTime(limits: limits)
            .Scale_Y_Continuous(limits: (0, maxQueueLength))
            .Scale_Color_Discrete(o => o.Series, Colors.Viridis )
            .Theme(dark:false, legend: Position.Bottom)
```

Unfortunately, my time series have timespans of  once per second over 10 minutes.

**Comment by pablofrommars** [comment]
Sampling below minute is not supported, my analysis rarely use higher frequency data.

I can work on providing a generic time scale users can derive to compute breaks and fit use cases.

I am interested to know how people use the library ie. type of project.

**Comment by 23min** [comment]
I'm visualizing events occuring in a system that occur as part of load testing. A test can be as short as 10 minutes, with many 1000's of data points over a dozen of series.
A minute is like a century and visualizing high frequency time series gives us insights that we could not get on a per-minute basis.

I would be very interested in a generic time scale!
I have only quickly looked at the part of the source code that handles the discrete datetime scaling. It would probably cost me considerable time to implement something and get it right :)

**Comment by pablofrommars** [comment]
Ideally, what breaks would you like to see? What time spans would you use?

I will keep the implementation as functional as possible to play nicely with F#

**Comment by pablofrommars** [comment]
May I ask you provide a data sample that triggers the error (csv, json, in-line c# code, whatever works for you)?

Just want to rule out other bugs

**Comment by 23min** [comment]
I can send you a json via email? I prefer not to post. 
To answer your previous question. I think one second resolution is quite enough. What I hoped was that the DateTime scale would behave like a scatter plot. Is that an idea, to plot on Ticks, but to label on some DateTime interval?

**Comment by 23min** [comment]
Btw the sample provided in my initial post triggers the problem too. I just reduced it to three points to isolate the problem.

**Comment by pablofrommars** [comment]
That actually would make a lot of sense to plot in “event time” rather than continuous, especially when data is not periodically sampled. 

No need for more data, what you provided will do!

Unlikely I will have a go at it before Monday, beautiful weather planned.

**Comment by 23min** [comment]
Awesome! Yes, first things first. Enjoy the sun.

**Comment by 23min** [comment]
Hi! Managed to work around it by using milliseconds (double, on a continuous scale) instead of LocalDateTime and using a custom formatter to format the labels (converting a Timespan to `hh\\:mm\\:ss'.)
That seems to work fine! So perhaps no code changes necessary.
I'm running into some other things but I can create separate issues for that.

**Comment by pablofrommars** [comment]
Glad you found a workaround. The “generic” scale will be implemented shortly.

Please open separate issues if you are experiencing misbehaviors.

**Comment by jan-ai** [comment]
"closed" with latest version at https://github.com/jan-ai/GGNet. See my comment on #8
