### ISSUE TITLE
System.NullReferenceException while rendering data

### ISSUE THREAD

**Issue by jan-ai** [pablofrommars/GGNet#7]
While rending data an System.NullReferenceException in Data/Data.cs line 409 is thrown.

` for (int g = 0; g < panel.Geoms.Count; g++)`

stack trace
>	GGNet.dll!GGNet.Data<(Helper.Database.Models.DbTask.Types, Helper.Database.Models.TaskHistory.States, string, double?), Helper.Database.Models.DbTask.Types, double>.RunLegend(bool first) Zeile 409	C#
 	GGNet.dll!GGNet.Data<(Helper.Database.Models.DbTask.Types, Helper.Database.Models.TaskHistory.States, string, double?), Helper.Database.Models.DbTask.Types, double>.Render(bool first) Zeile 446	C#
 	GGNet.dll!GGNet.Components.Plot<(Helper.Database.Models.DbTask.Types, Helper.Database.Models.TaskHistory.States, string, double?), Helper.Database.Models.DbTask.Types, double>.Render(bool firstRender) Zeile 37	C#
 	GGNet.dll!GGNet.Components.Plot<(Helper.Database.Models.DbTask.Types, Helper.Database.Models.TaskHistory.States, string, double?), Helper.Database.Models.DbTask.Types, double>.OnInitialized() Zeile 32	C#
 	[Externer Code]	

The exception is thrown because panel == NULL. I guess the cause for this is an empty data source (groupTasks) for the following setup

```
tasksPlot = Plot.New (groupTasks, x: o => o.typ, y: o => o.data ?? 0)
                .Geom_Bar (position: PositionAdjustment.Dodge, width: 0.5, tooltip: o => Math.Round (o.data ?? 0, 2).ToString ())
                .Scale_X_Discrete (expand: (0.0, 0.1, 0, 0.1), formatter: labeller)
                .Scale_Fill_Discrete (o => o.state, Colors.Viridis, direction: -1)
                .Facet_Wrap (selector: o => o.label, freeY: true)
                .XLab ("kind of task")
                .Theme (dark: false, legend: Position.Bottom);

```

While obviously it's discussable if an empty data source makes sense, from my point of view it should generate an empty chart and at least should not "crash" on rending, but rather throw an exception on setup (if the prefered option (an empty chart) is not the way to go)

**Comment by pablofrommars** [comment]
Have to look into what are the guidelines on exception handling in Blazor. Users should be able to decide what to do in case of errors.

Thanks for reporting

**Comment by jan-ai** [comment]
Just as a note. While for the here mentioned chart it doesn't matter too much, if it will be shown with empty data or not, I have an additional chart, which will be updated regularly. For that chart it will be a problem if I have to replace the chart by something like “here should be a chart, but currently no data is available” and 10 seconds later a chart will be shown again and so on ..

**Comment by pablofrommars** [comment]
I am leaning towards GGNet should provide enough information for users to handle and recover from errors. Ultimately, users are in charge of providing valid data.

My recommandation for the time being would be to display a [spinner](https://getbootstrap.com/docs/4.4/components/spinners/) or whatever alternate view while waiting for data. 

The issue is added to the roadmap.
