### ISSUE TITLE
x-Axis LocalDateTime based chart can't be set to "include" values outside the source data

### ISSUE THREAD

**Issue by jan-ai** [pablofrommars/GGNet#8]
I tried to find a way to create a chart which shows values for the last 2 hours. I guess I should use the `expand` fields of `Scale_X_Discrete_DateTime`

```
            past2hPlot = Plot.New (callers.Values.Where (c => c.StartTimeOffset > minLimit),
                    x: o =>
                    {
                        var dto = o.StartTimeOffset;
                        return LocalDateTime.FromDateTime (dto.AddSeconds (-dto.Second).ToLocalTime ().DateTime);
                    },
                    y: o => 1.0)
                .Geom_Bar (position: PositionAdjustment.Stack, width: 0.5)
                .Scale_X_Discrete_DateTime (expand: (0.0, 0.1, 0, 0.1))
                .Scale_Fill_Discrete (o => o.Lang ?? String.Empty, Colors.Viridis, direction: -1)
                //.Facet_Wrap (selector: o => o.label, freeY: true)
                .XLab ("Anrufer")
                .Theme (dark: false, legend: Position.Bottom);

```
Nevertheless it looks like the `Set` function in class `DateTimePosition` which calls `SetRange` function is based on doubles instead of some sort of time values. 

Also from what I see from code the calculation of minimum and maximum of the `limits` fields in` Scale_X_Discrete_DateTime` used in `Set` function does only work for limits which are present in the source set itself. If a limit is specified which is not included in the source set all data will be shown in the chart ignoring any limits. There should be a less or greater than comparission form my point of view.

**Comment by pablofrommars** [comment]
Limits can be seen as a filter of the data source. Expand is the parameter you are after.

**Comment by pablofrommars** [comment]
Time scales will be refactored in a later release as requested by other users. Can’t promise any ETA for now.

**Comment by jan-ai** [comment]
> Limits can be seen as a filter of the data source. Expand is the parameter you are after.

Just to double check with @pablofrommars. Currently expand will not work for LocalDateTime x-axis, right? As far as I can see it uses typeof(double) and is based on the values of the data set. If there is no data in the data set, which marks the desired boundaries of the x-axis it will not work.

**Comment by jan-ai** [comment]
I added an axis which is based on DateTime and continues data. This allows using expand limits information. I also added possibility to dynamically updated those limits on chart refresh. See page visitors as an example at https://github.com/jan-ai/GGNet

![visitors](https://user-images.githubusercontent.com/52295393/103322181-774e1b00-4a3d-11eb-901b-62279e113ecb.gif)
