### ISSUE TITLE
it's not possible to use time-based x-axis for sources having entries using different seconds within a minute

### ISSUE THREAD

**Issue by jan-ai** [pablofrommars/GGNet#9]
The x position and width will not be calulated correctly for charts having more than 1 entry per minute in the their source set. The x position will be NaN (as well as the width) resulting in not showing any information in the chart.

class `DateTimePosition` returns double.NaN when a value (on x-axis) cannot be found. Which in fact should not happen, but … 

```
        public override double Map(LocalDateTime key)
        {
            var index = values.IndexOf(key);
            if (index < 0)
            {
                return double.NaN;
            }

            return index;
        }

```
… the function `Train` will skip to add entries in case the sampling rate is less than one minute.

```
        public override void Train(LocalDateTime key)
        {
            if (values.Count > 0)

            ...

                var current = values[values.Count - 1];
                if (current.Date == key.Date)
                {
                    current = current.Plus(sampling);

                    while(current <= key)
                    {
                        values.Add(current);

                        current = current.Plus(sampling);
                    }
                }

```

The way it's currently setup also leads to problems if samples have different minutes, but are in the range of less than 60 seconds. What was the reason to use a "sampling frequency" here? My expectation would be to remove this "sampling" completly, as I want to display data within a period of 1 minute. Anyway if sampling is used here to combine entries (what ever that would mean) the lookup function `Map` should handle that correctly.

**Comment by pablofrommars** [comment]
Duplicate #4
